n = input('Digite Algo: ')
print(f'o tipo primitivo deste valor é {type(n)}')
print(f'só tem espaços? {n.isspace()}')
print(f'é um número? {n.isnumeric()}')
print(f'é alfabetico? {n.isalpha()}')
print(f'é alfanumerico? {n.isalnum()}')
print(f'está em maiusculo? {n.isupper()}')
print(f'está em minusculo? {n.islower()}')
print(f'está capitalizada? {n.istitle()}')